USE gctstucom;

# Create Table CONNECTIONS
CREATE TABLE IF NOT EXISTS CONNECTIONS (
	CONN_ID INT NOT NULL,
    REGISTER VARCHAR(10),
    GCT_MAIL VARCHAR(30),
    PASSWORD VARCHAR(255),
    FIRST_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50),
    YEAR_OF_JOINING VARCHAR(5),
    DEPARTMENT VARCHAR(10),
    FIELD_OF_INTEREST VARCHAR(100),
    CREATED_ON DATETIME,
    PRIMARY KEY (REGISTER) 
);

# Describe Table CONNECTIONS
DESC CONNECTIONS;

# Select Table CONNECTIONS
SELECT * FROM CONNECTIONS;

# Records (Row) Count in Table CONNECTIONS
SELECT COUNT(*) FROM CONNECTIONS;

    
